# Generated by Django 4.2.16 on 2024-09-19 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='generation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='generation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
